//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 11:09:46 PM CET 
//


package kamikaze.esb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Capteur complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Capteur">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ligne" type="{http://www.example.org/MockTrain}Ligne"/>
 *         &lt;element name="wagon" type="{http://www.example.org/MockTrain}Wagon"/>
 *         &lt;element name="train" type="{http://www.example.org/MockTrain}Train"/>
 *         &lt;element name="canton" type="{http://www.example.org/MockTrain}Canton"/>
 *         &lt;element name="station" type="{http://www.example.org/MockTrain}Station"/>
 *       &lt;/choice>
 *       &lt;attribute name="idCapteur" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Capteur", propOrder = {
    "ligneOrWagonOrTrain"
})
public class Capteur {

    @XmlElements({
        @XmlElement(name = "train", type = Train.class),
        @XmlElement(name = "wagon", type = Wagon.class),
        @XmlElement(name = "station", type = Station.class),
        @XmlElement(name = "canton", type = Canton.class),
        @XmlElement(name = "ligne", type = Ligne.class)
    })
    protected List<Object> ligneOrWagonOrTrain;
    @XmlAttribute
    protected Integer idCapteur;
    @XmlAttribute
    protected Double longitude;
    @XmlAttribute
    protected Double latitude;

    /**
     * Gets the value of the ligneOrWagonOrTrain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ligneOrWagonOrTrain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLigneOrWagonOrTrain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Train }
     * {@link Wagon }
     * {@link Station }
     * {@link Canton }
     * {@link Ligne }
     * 
     * 
     */
    public List<Object> getLigneOrWagonOrTrain() {
        if (ligneOrWagonOrTrain == null) {
            ligneOrWagonOrTrain = new ArrayList<Object>();
        }
        return this.ligneOrWagonOrTrain;
    }

    public void setLigneOrWagonOrTrain(List<Object> ligneOrWagonOrTrain) {
		this.ligneOrWagonOrTrain = ligneOrWagonOrTrain;
	}

	/**
     * Gets the value of the idCapteur property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdCapteur() {
        return idCapteur;
    }

    /**
     * Sets the value of the idCapteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdCapteur(Integer value) {
        this.idCapteur = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLongitude(Double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLatitude(Double value) {
        this.latitude = value;
    }

}
