//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 11:09:46 PM CET 
//


package kamikaze.esb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mess" type="{http://www.example.org/MockTrain}Event"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="ligne" type="{http://www.example.org/MockTrain}Ligne"/>
 *           &lt;element name="wagon" type="{http://www.example.org/MockTrain}Wagon"/>
 *           &lt;element name="train" type="{http://www.example.org/MockTrain}Train"/>
 *           &lt;element name="canton" type="{http://www.example.org/MockTrain}Canton"/>
 *           &lt;element name="station" type="{http://www.example.org/MockTrain}Station"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mess",
    "ligneOrWagonOrTrain"
})
@XmlRootElement(name = "envoyerEventServiceMixToSI")
public class EnvoyerEventServiceMixToSI {

    @XmlElement(required = true)
    protected Event mess;
    @XmlElements({
        @XmlElement(name = "station", type = Station.class),
        @XmlElement(name = "canton", type = Canton.class),
        @XmlElement(name = "train", type = Train.class),
        @XmlElement(name = "ligne", type = Ligne.class),
        @XmlElement(name = "wagon", type = Wagon.class)
    })
    protected List<Object> ligneOrWagonOrTrain;

    /**
     * Gets the value of the mess property.
     * 
     * @return
     *     possible object is
     *     {@link Event }
     *     
     */
    public Event getMess() {
        return mess;
    }

    /**
     * Sets the value of the mess property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setMess(Event value) {
        this.mess = value;
    }

    /**
     * Gets the value of the ligneOrWagonOrTrain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ligneOrWagonOrTrain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLigneOrWagonOrTrain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Station }
     * {@link Canton }
     * {@link Train }
     * {@link Ligne }
     * {@link Wagon }
     * 
     * 
     */
    public List<Object> getLigneOrWagonOrTrain() {
        if (ligneOrWagonOrTrain == null) {
            ligneOrWagonOrTrain = new ArrayList<Object>();
        }
        return this.ligneOrWagonOrTrain;
    }

	public void setLigneOrWagonOrTrain(List<Object> ligneOrWagonOrTrain) {
		this.ligneOrWagonOrTrain = ligneOrWagonOrTrain;
	}
    

}
