//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 11:09:46 PM CET 
//


package kamikaze.esb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capteur" type="{http://www.example.org/MockTrain}Capteur"/>
 *         &lt;element name="type" type="{http://www.example.org/MockTrain}EventType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idEvent" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="criticite" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="libelle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "capteur",
    "type"
})
public class Event {

    @XmlElement(required = true)
    protected Capteur capteur;
    @XmlElement(required = true)
    protected EventType type;
    @XmlAttribute
    protected Integer idEvent;
    @XmlAttribute
    protected Integer criticite;
    @XmlAttribute
    protected String libelle;

    /**
     * Gets the value of the capteur property.
     * 
     * @return
     *     possible object is
     *     {@link Capteur }
     *     
     */
    public Capteur getCapteur() {
        return capteur;
    }

    /**
     * Sets the value of the capteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link Capteur }
     *     
     */
    public void setCapteur(Capteur value) {
        this.capteur = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setType(EventType value) {
        this.type = value;
    }

    /**
     * Gets the value of the idEvent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdEvent() {
        return idEvent;
    }

    /**
     * Sets the value of the idEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdEvent(Integer value) {
        this.idEvent = value;
    }

    /**
     * Gets the value of the criticite property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCriticite() {
        return criticite;
    }

    /**
     * Sets the value of the criticite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCriticite(Integer value) {
        this.criticite = value;
    }

    /**
     * Gets the value of the libelle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibelle() {
        return libelle;
    }

    /**
     * Sets the value of the libelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibelle(String value) {
        this.libelle = value;
    }

}
