//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.14 at 03:12:36 AM CEST 
//


package kamikaze.esb.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncidentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncidentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SOCIAL MOVEMENT"/>
 *     &lt;enumeration value="SUSPECT_PACKAGE"/>
 *     &lt;enumeration value="UNACTIVE_SENSOR"/>
 *     &lt;enumeration value="LOCKED_DOOR"/>
 *     &lt;enumeration value="SAFETY_DISTANCE"/>
 *     &lt;enumeration value="ELECTRIC_FAILURE"/>
 *     &lt;enumeration value="EMERGENCY_CALL"/>
 *     &lt;enumeration value="EXCESSIVE_SPEED"/>
 *     &lt;enumeration value="UNEXPECTED_STOP"/>
 *     &lt;enumeration value="DEFAULT_EQUIPMENT"/>
 *     &lt;enumeration value="COLLISION_RISK"/>
 *     &lt;enumeration value="COLLISION"/>
 *     &lt;enumeration value="BOMB_ALERT"/>
 *     &lt;enumeration value="MISSED_STATION"/>
 *     &lt;enumeration value="GAS_LEAK"/>
 *     &lt;enumeration value="LOST_SYNCHRONISATION"/>
 *     &lt;enumeration value="FIRE"/>
 *     &lt;enumeration value="SNOW_STORM"/>
 *     &lt;enumeration value="FLOOD"/>
 *     &lt;enumeration value="PASSENGER_ACCIDENT"/>
 *     &lt;enumeration value="FALLEN_PASSENGER"/>
 *     &lt;enumeration value="OBSTACLE_IN_WAY"/>
 *     &lt;enumeration value="PASSENGER_ACCIDENT"/>
 *     &lt;enumeration value="SICK_PASSENGER"/>
 *     &lt;enumeration value="ANORMAL_TEMPERATURE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IncidentType")
@XmlEnum
public enum IncidentType {

    @XmlEnumValue("SOCIAL MOVEMENT")
    SOCIAL_MOVEMENT("SOCIAL MOVEMENT"),
    SUSPECT_PACKAGE("SUSPECT_PACKAGE"),
    UNACTIVE_SENSOR("UNACTIVE_SENSOR"),
    LOCKED_DOOR("LOCKED_DOOR"),
    SAFETY_DISTANCE("SAFETY_DISTANCE"),
    ELECTRIC_FAILURE("ELECTRIC_FAILURE"),
    EMERGENCY_CALL("EMERGENCY_CALL"),
    EXCESSIVE_SPEED("EXCESSIVE_SPEED"),
    UNEXPECTED_STOP("UNEXPECTED_STOP"),
    DEFAULT_EQUIPMENT("DEFAULT_EQUIPMENT"),
    COLLISION_RISK("COLLISION_RISK"),
    COLLISION("COLLISION"),
    BOMB_ALERT("BOMB_ALERT"),
    MISSED_STATION("MISSED_STATION"),
    GAS_LEAK("GAS_LEAK"),
    LOST_SYNCHRONISATION("LOST_SYNCHRONISATION"),
    FIRE("FIRE"),
    SNOW_STORM("SNOW_STORM"),
    FLOOD("FLOOD"),
    PASSENGER_ACCIDENT("PASSENGER_ACCIDENT"),
    FALLEN_PASSENGER("FALLEN_PASSENGER"),
    OBSTACLE_IN_WAY("OBSTACLE_IN_WAY"),
    SICK_PASSENGER("SICK_PASSENGER"),
    ANORMAL_TEMPERATURE("ANORMAL_TEMPERATURE");
    private final String value;

    IncidentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncidentType fromValue(String v) {
        for (IncidentType c: IncidentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
