//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 11:09:46 PM CET 
//


package kamikaze.esb.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kamikaze.esb.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kamikaze.esb.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link TypeWagon }
     * 
     */
    public TypeWagon createTypeWagon() {
        return new TypeWagon();
    }

    /**
     * Create an instance of {@link Ligne }
     * 
     */
    public Ligne createLigne() {
        return new Ligne();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link Train }
     * 
     */
    public Train createTrain() {
        return new Train();
    }

    /**
     * Create an instance of {@link Wagon }
     * 
     */
    public Wagon createWagon() {
        return new Wagon();
    }

    /**
     * Create an instance of {@link EnvoyerEventServiceMixToSI }
     * 
     */
    public EnvoyerEventServiceMixToSI createEnvoyerEventServiceMixToSI() {
        return new EnvoyerEventServiceMixToSI();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link EnvoyerEventToServiceMix }
     * 
     */
    public EnvoyerEventToServiceMix createEnvoyerEventToServiceMix() {
        return new EnvoyerEventToServiceMix();
    }

    /**
     * Create an instance of {@link Canton }
     * 
     */
    public Canton createCanton() {
        return new Canton();
    }

    /**
     * Create an instance of {@link Troncon }
     * 
     */
    public Troncon createTroncon() {
        return new Troncon();
    }

    /**
     * Create an instance of {@link Capteur }
     * 
     */
    public Capteur createCapteur() {
        return new Capteur();
    }

}
