//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.25 at 12:38:07 AM CET 
//


package kamikaze.esb.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kamikaze.esb.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kamikaze.esb.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MockInfoTrafic }
     * 
     */
    public MockInfoTrafic createMockInfoTrafic() {
        return new MockInfoTrafic();
    }

    /**
     * Create an instance of {@link IncSimpleMessage }
     * 
     */
    public IncSimpleMessage createIncSimpleMessage() {
        return new IncSimpleMessage();
    }

    /**
     * Create an instance of {@link Troncon }
     * 
     */
    public Troncon createTroncon() {
        return new Troncon();
    }

    /**
     * Create an instance of {@link Train }
     * 
     */
    public Train createTrain() {
        return new Train();
    }

    /**
     * Create an instance of {@link Ligne }
     * 
     */
    public Ligne createLigne() {
        return new Ligne();
    }

    /**
     * Create an instance of {@link LibelleEventType }
     * 
     */
    public LibelleEventType createLibelleEventType() {
        return new LibelleEventType();
    }

    /**
     * Create an instance of {@link EnvoiEventMessage }
     * 
     */
    public EnvoiEventMessage createEnvoiEventMessage() {
        return new EnvoiEventMessage();
    }

    /**
     * Create an instance of {@link EnvoiInfoTraficToSI }
     * 
     */
    public EnvoiInfoTraficToSI createEnvoiInfoTraficToSI() {
        return new EnvoiInfoTraficToSI();
    }

    /**
     * Create an instance of {@link IncidentSimple }
     * 
     */
    public IncidentSimple createIncidentSimple() {
        return new IncidentSimple();
    }

    /**
     * Create an instance of {@link EnvoiEventMessageToSI }
     * 
     */
    public EnvoiEventMessageToSI createEnvoiEventMessageToSI() {
        return new EnvoiEventMessageToSI();
    }

    /**
     * Create an instance of {@link Wagon }
     * 
     */
    public Wagon createWagon() {
        return new Wagon();
    }

    /**
     * Create an instance of {@link IncidentCritique }
     * 
     */
    public IncidentCritique createIncidentCritique() {
        return new IncidentCritique();
    }

    /**
     * Create an instance of {@link EventMessage }
     * 
     */
    public EventMessage createEventMessage() {
        return new EventMessage();
    }

    /**
     * Create an instance of {@link LibelleIncidentCritique }
     * 
     */
    public LibelleIncidentCritique createLibelleIncidentCritique() {
        return new LibelleIncidentCritique();
    }

    /**
     * Create an instance of {@link EnvoiIncCritiqueMessage }
     * 
     */
    public EnvoiIncCritiqueMessage createEnvoiIncCritiqueMessage() {
        return new EnvoiIncCritiqueMessage();
    }

    /**
     * Create an instance of {@link LibelleIncidentSimple }
     * 
     */
    public LibelleIncidentSimple createLibelleIncidentSimple() {
        return new LibelleIncidentSimple();
    }

    /**
     * Create an instance of {@link Capteur }
     * 
     */
    public Capteur createCapteur() {
        return new Capteur();
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link EnvoiIncSimpleMessage }
     * 
     */
    public EnvoiIncSimpleMessage createEnvoiIncSimpleMessage() {
        return new EnvoiIncSimpleMessage();
    }

    /**
     * Create an instance of {@link IncCritiqueMessage }
     * 
     */
    public IncCritiqueMessage createIncCritiqueMessage() {
        return new IncCritiqueMessage();
    }

    /**
     * Create an instance of {@link Canton }
     * 
     */
    public Canton createCanton() {
        return new Canton();
    }

    /**
     * Create an instance of {@link Sujet }
     * 
     */
    public Sujet createSujet() {
        return new Sujet();
    }

    /**
     * Create an instance of {@link EnvoiIncSimpleMessageToSI }
     * 
     */
    public EnvoiIncSimpleMessageToSI createEnvoiIncSimpleMessageToSI() {
        return new EnvoiIncSimpleMessageToSI();
    }

    /**
     * Create an instance of {@link EnvoiIncCritiqueMessageToSI }
     * 
     */
    public EnvoiIncCritiqueMessageToSI createEnvoiIncCritiqueMessageToSI() {
        return new EnvoiIncCritiqueMessageToSI();
    }

    /**
     * Create an instance of {@link Typewagon }
     * 
     */
    public Typewagon createTypewagon() {
        return new Typewagon();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

}
