//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 11:09:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/MockTrain", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kamikaze.esb.model;
