//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.25 at 12:38:07 AM CET 
//


package kamikaze.esb.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sujet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sujet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ligne" type="{http://www.example.org/Event}ligne"/>
 *         &lt;element name="wagon" type="{http://www.example.org/Event}wagon"/>
 *         &lt;element name="canton" type="{http://www.example.org/Event}canton"/>
 *         &lt;element name="station" type="{http://www.example.org/Event}station"/>
 *         &lt;element name="troncon" type="{http://www.example.org/Event}troncon"/>
 *         &lt;element name="train" type="{http://www.example.org/Event}train"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sujet", propOrder = {
    "ligne",
    "wagon",
    "canton",
    "station",
    "troncon",
    "train"
})
public class Sujet {

    protected Ligne ligne;
    protected Wagon wagon;
    protected Canton canton;
    protected Station station;
    protected Troncon troncon;
    protected Train train;

    /**
     * Gets the value of the ligne property.
     * 
     * @return
     *     possible object is
     *     {@link Ligne }
     *     
     */
    public Ligne getLigne() {
        return ligne;
    }

    /**
     * Sets the value of the ligne property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ligne }
     *     
     */
    public void setLigne(Ligne value) {
        this.ligne = value;
    }

    /**
     * Gets the value of the wagon property.
     * 
     * @return
     *     possible object is
     *     {@link Wagon }
     *     
     */
    public Wagon getWagon() {
        return wagon;
    }

    /**
     * Sets the value of the wagon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wagon }
     *     
     */
    public void setWagon(Wagon value) {
        this.wagon = value;
    }

    /**
     * Gets the value of the canton property.
     * 
     * @return
     *     possible object is
     *     {@link Canton }
     *     
     */
    public Canton getCanton() {
        return canton;
    }

    /**
     * Sets the value of the canton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Canton }
     *     
     */
    public void setCanton(Canton value) {
        this.canton = value;
    }

    /**
     * Gets the value of the station property.
     * 
     * @return
     *     possible object is
     *     {@link Station }
     *     
     */
    public Station getStation() {
        return station;
    }

    /**
     * Sets the value of the station property.
     * 
     * @param value
     *     allowed object is
     *     {@link Station }
     *     
     */
    public void setStation(Station value) {
        this.station = value;
    }

    /**
     * Gets the value of the troncon property.
     * 
     * @return
     *     possible object is
     *     {@link Troncon }
     *     
     */
    public Troncon getTroncon() {
        return troncon;
    }

    /**
     * Sets the value of the troncon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Troncon }
     *     
     */
    public void setTroncon(Troncon value) {
        this.troncon = value;
    }

    /**
     * Gets the value of the train property.
     * 
     * @return
     *     possible object is
     *     {@link Train }
     *     
     */
    public Train getTrain() {
        return train;
    }

    /**
     * Sets the value of the train property.
     * 
     * @param value
     *     allowed object is
     *     {@link Train }
     *     
     */
    public void setTrain(Train value) {
        this.train = value;
    }

}
