//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 11:09:46 PM CET 
//


package kamikaze.esb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Troncon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Troncon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stationDepart" type="{http://www.example.org/MockTrain}Station"/>
 *         &lt;element name="stationArrivee" type="{http://www.example.org/MockTrain}Station"/>
 *         &lt;element name="listeCantons" type="{http://www.example.org/MockTrain}Canton" maxOccurs="unbounded"/>
 *         &lt;element name="capteur" type="{http://www.example.org/MockTrain}Capteur" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Troncon", propOrder = {
    "stationDepart",
    "stationArrivee",
    "listeCantons",
    "capteur"
})
public class Troncon {

    @XmlElement(required = true)
    protected Station stationDepart;
    @XmlElement(required = true)
    protected Station stationArrivee;
    @XmlElement(required = true)
    protected List<Canton> listeCantons;
    @XmlElement(required = true)
    protected List<Capteur> capteur;

    /**
     * Gets the value of the stationDepart property.
     * 
     * @return
     *     possible object is
     *     {@link Station }
     *     
     */
    public Station getStationDepart() {
        return stationDepart;
    }

    /**
     * Sets the value of the stationDepart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Station }
     *     
     */
    public void setStationDepart(Station value) {
        this.stationDepart = value;
    }

    /**
     * Gets the value of the stationArrivee property.
     * 
     * @return
     *     possible object is
     *     {@link Station }
     *     
     */
    public Station getStationArrivee() {
        return stationArrivee;
    }

    /**
     * Sets the value of the stationArrivee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Station }
     *     
     */
    public void setStationArrivee(Station value) {
        this.stationArrivee = value;
    }

    /**
     * Gets the value of the listeCantons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listeCantons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListeCantons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Canton }
     * 
     * 
     */
    public List<Canton> getListeCantons() {
        if (listeCantons == null) {
            listeCantons = new ArrayList<Canton>();
        }
        return this.listeCantons;
    }

    public void setListeCantons(List<Canton> listeCantons) {
		this.listeCantons = listeCantons;
	}



	/**
     * Gets the value of the capteur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capteur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapteur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Capteur }
     * 
     * 
     */
    public List<Capteur> getCapteur() {
        if (capteur == null) {
            capteur = new ArrayList<Capteur>();
        }
        return this.capteur;
    }
	public void setCapteur(List<Capteur> capteur) {
		this.capteur = capteur;
	}
}
