//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.25 at 12:38:07 AM CET 
//


package kamikaze.esb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for troncon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="troncon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StationDepart" type="{http://www.example.org/Event}station"/>
 *         &lt;element name="StationArrivee" type="{http://www.example.org/Event}station"/>
 *         &lt;element name="listeCantons" type="{http://www.example.org/Event}canton" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="taille" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "troncon", propOrder = {
    "stationDepart",
    "stationArrivee",
    "listeCantons"
})
public class Troncon {

    @XmlElement(name = "StationDepart", required = true)
    protected Station stationDepart;
    @XmlElement(name = "StationArrivee", required = true)
    protected Station stationArrivee;
    @XmlElement(required = true)
    protected List<Canton> listeCantons;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected Float taille;

    /**
     * Gets the value of the stationDepart property.
     * 
     * @return
     *     possible object is
     *     {@link Station }
     *     
     */
    public Station getStationDepart() {
        return stationDepart;
    }

    /**
     * Sets the value of the stationDepart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Station }
     *     
     */
    public void setStationDepart(Station value) {
        this.stationDepart = value;
    }

    /**
     * Gets the value of the stationArrivee property.
     * 
     * @return
     *     possible object is
     *     {@link Station }
     *     
     */
    public Station getStationArrivee() {
        return stationArrivee;
    }

    /**
     * Sets the value of the stationArrivee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Station }
     *     
     */
    public void setStationArrivee(Station value) {
        this.stationArrivee = value;
    }

    /**
     * Gets the value of the listeCantons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listeCantons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListeCantons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Canton }
     * 
     * 
     */
    public List<Canton> getListeCantons() {
        if (listeCantons == null) {
            listeCantons = new ArrayList<Canton>();
        }
        return this.listeCantons;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the taille property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTaille() {
        return taille;
    }

    /**
     * Sets the value of the taille property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTaille(Float value) {
        this.taille = value;
    }

}
