//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.21 at 11:09:46 PM CET 
//


package kamikaze.esb.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Wagon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Wagon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capteur" type="{http://www.example.org/MockTrain}Capteur" maxOccurs="unbounded"/>
 *         &lt;element name="train" type="{http://www.example.org/MockTrain}Train"/>
 *         &lt;element name="typewagon" type="{http://www.example.org/MockTrain}TypeWagon"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idWagon" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Wagon", propOrder = {
    "capteur",
    "train",
    "typewagon"
})
public class Wagon {

    @XmlElement(required = true)
    protected List<Capteur> capteur;
    @XmlElement(required = true)
    protected Train train;
    @XmlElement(required = true)
    protected TypeWagon typewagon;
    @XmlAttribute
    protected Integer idWagon;

    /**
     * Gets the value of the capteur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capteur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapteur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Capteur }
     * 
     * 
     */
    public List<Capteur> getCapteur() {
        if (capteur == null) {
            capteur = new ArrayList<Capteur>();
        }
        return this.capteur;
    }

    public void setCapteur(List<Capteur> capteur) {
		this.capteur = capteur;
	}

	/**
     * Gets the value of the train property.
     * 
     * @return
     *     possible object is
     *     {@link Train }
     *     
     */
    public Train getTrain() {
        return train;
    }

    /**
     * Sets the value of the train property.
     * 
     * @param value
     *     allowed object is
     *     {@link Train }
     *     
     */
    public void setTrain(Train value) {
        this.train = value;
    }

    /**
     * Gets the value of the typewagon property.
     * 
     * @return
     *     possible object is
     *     {@link TypeWagon }
     *     
     */
    public TypeWagon getTypewagon() {
        return typewagon;
    }

    /**
     * Sets the value of the typewagon property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeWagon }
     *     
     */
    public void setTypewagon(TypeWagon value) {
        this.typewagon = value;
    }

    /**
     * Gets the value of the idWagon property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdWagon() {
        return idWagon;
    }

    /**
     * Sets the value of the idWagon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdWagon(Integer value) {
        this.idWagon = value;
    }

}
