//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.24 at 02:13:20 AM CET 
//


package modeleMessages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.example.org/MockTrain}EventType"/>
 *         &lt;sequence>
 *           &lt;choice>
 *             &lt;element name="Canton" type="{http://www.example.org/MockTrain}Canton"/>
 *             &lt;element name="Train" type="{http://www.example.org/MockTrain}Train"/>
 *             &lt;element name="Troncon" type="{http://www.example.org/MockTrain}Troncon"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="idEvent" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="criticite" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="libelle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "type",
    "canton",
    "train",
    "troncon"
})
public class Event {

    @XmlElement(required = true)
    protected EventType type;
    @XmlElement(name = "Canton")
    protected Canton canton;
    @XmlElement(name = "Train")
    protected Train train;
    @XmlElement(name = "Troncon")
    protected Troncon troncon;
    @XmlAttribute(name = "idEvent")
    protected Integer idEvent;
    @XmlAttribute(name = "criticite")
    protected String criticite;
    @XmlAttribute(name = "libelle")
    protected String libelle;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setType(EventType value) {
        this.type = value;
    }

    /**
     * Gets the value of the canton property.
     * 
     * @return
     *     possible object is
     *     {@link Canton }
     *     
     */
    public Canton getCanton() {
        return canton;
    }

    /**
     * Sets the value of the canton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Canton }
     *     
     */
    public void setCanton(Canton value) {
        this.canton = value;
    }

    /**
     * Gets the value of the train property.
     * 
     * @return
     *     possible object is
     *     {@link Train }
     *     
     */
    public Train getTrain() {
        return train;
    }

    /**
     * Sets the value of the train property.
     * 
     * @param value
     *     allowed object is
     *     {@link Train }
     *     
     */
    public void setTrain(Train value) {
        this.train = value;
    }

    /**
     * Gets the value of the troncon property.
     * 
     * @return
     *     possible object is
     *     {@link Troncon }
     *     
     */
    public Troncon getTroncon() {
        return troncon;
    }

    /**
     * Sets the value of the troncon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Troncon }
     *     
     */
    public void setTroncon(Troncon value) {
        this.troncon = value;
    }

    /**
     * Gets the value of the idEvent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdEvent() {
        return idEvent;
    }

    /**
     * Sets the value of the idEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdEvent(Integer value) {
        this.idEvent = value;
    }

    /**
     * Gets the value of the criticite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCriticite() {
        return criticite;
    }

    /**
     * Sets the value of the criticite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCriticite(String value) {
        this.criticite = value;
    }

    /**
     * Gets the value of the libelle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibelle() {
        return libelle;
    }

    /**
     * Sets the value of the libelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibelle(String value) {
        this.libelle = value;
    }

}
