//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.24 at 02:13:20 AM CET 
//


package modeleMessages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Ligne complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ligne">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listeTrains" type="{http://www.example.org/MockTrain}Train" maxOccurs="unbounded"/>
 *         &lt;element name="listeTroncons" type="{http://www.example.org/MockTrain}Troncon" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idLigne" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="nomLigne" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="heurePremierTrain" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="heureDernierTrain" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="capaciteCirculation" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="nombreCanton" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="kilometrageTotal" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="commentaireLigne" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="capaciteMaxDeVoyageur" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ligne", propOrder = {
    "listeTrains",
    "listeTroncons"
})
public class Ligne {

    @XmlElement(required = true)
    protected List<Train> listeTrains;
    @XmlElement(required = true)
    protected List<Troncon> listeTroncons;
    @XmlAttribute(name = "idLigne")
    protected Integer idLigne;
    @XmlAttribute(name = "nomLigne")
    protected String nomLigne;
    @XmlAttribute(name = "heurePremierTrain")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar heurePremierTrain;
    @XmlAttribute(name = "heureDernierTrain")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar heureDernierTrain;
    @XmlAttribute(name = "capaciteCirculation")
    protected Double capaciteCirculation;
    @XmlAttribute(name = "nombreCanton")
    protected Double nombreCanton;
    @XmlAttribute(name = "kilometrageTotal")
    protected Float kilometrageTotal;
    @XmlAttribute(name = "commentaireLigne")
    protected String commentaireLigne;
    @XmlAttribute(name = "capaciteMaxDeVoyageur")
    protected Double capaciteMaxDeVoyageur;

    /**
     * Gets the value of the listeTrains property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listeTrains property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListeTrains().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Train }
     * 
     * 
     */
    public List<Train> getListeTrains() {
        if (listeTrains == null) {
            listeTrains = new ArrayList<Train>();
        }
        return this.listeTrains;
    }

    /**
     * Gets the value of the listeTroncons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listeTroncons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListeTroncons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Troncon }
     * 
     * 
     */
    public List<Troncon> getListeTroncons() {
        if (listeTroncons == null) {
            listeTroncons = new ArrayList<Troncon>();
        }
        return this.listeTroncons;
    }

    /**
     * Gets the value of the idLigne property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdLigne() {
        return idLigne;
    }

    /**
     * Sets the value of the idLigne property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdLigne(Integer value) {
        this.idLigne = value;
    }

    /**
     * Gets the value of the nomLigne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomLigne() {
        return nomLigne;
    }

    /**
     * Sets the value of the nomLigne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomLigne(String value) {
        this.nomLigne = value;
    }

    /**
     * Gets the value of the heurePremierTrain property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHeurePremierTrain() {
        return heurePremierTrain;
    }

    /**
     * Sets the value of the heurePremierTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHeurePremierTrain(XMLGregorianCalendar value) {
        this.heurePremierTrain = value;
    }

    /**
     * Gets the value of the heureDernierTrain property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getHeureDernierTrain() {
        return heureDernierTrain;
    }

    /**
     * Sets the value of the heureDernierTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setHeureDernierTrain(XMLGregorianCalendar value) {
        this.heureDernierTrain = value;
    }

    /**
     * Gets the value of the capaciteCirculation property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCapaciteCirculation() {
        return capaciteCirculation;
    }

    /**
     * Sets the value of the capaciteCirculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCapaciteCirculation(Double value) {
        this.capaciteCirculation = value;
    }

    /**
     * Gets the value of the nombreCanton property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNombreCanton() {
        return nombreCanton;
    }

    /**
     * Sets the value of the nombreCanton property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNombreCanton(Double value) {
        this.nombreCanton = value;
    }

    /**
     * Gets the value of the kilometrageTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getKilometrageTotal() {
        return kilometrageTotal;
    }

    /**
     * Sets the value of the kilometrageTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setKilometrageTotal(Float value) {
        this.kilometrageTotal = value;
    }

    /**
     * Gets the value of the commentaireLigne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentaireLigne() {
        return commentaireLigne;
    }

    /**
     * Sets the value of the commentaireLigne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentaireLigne(String value) {
        this.commentaireLigne = value;
    }

    /**
     * Gets the value of the capaciteMaxDeVoyageur property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCapaciteMaxDeVoyageur() {
        return capaciteMaxDeVoyageur;
    }

    /**
     * Sets the value of the capaciteMaxDeVoyageur property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCapaciteMaxDeVoyageur(Double value) {
        this.capaciteMaxDeVoyageur = value;
    }

}
