//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.24 at 02:13:20 AM CET 
//


package modeleMessages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Station complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Station">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capteur" type="{http://www.example.org/MockTrain}Capteur" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idStation" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="nomStation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Station", propOrder = {
    "capteur"
})
public class Station {

    @XmlElement(required = true)
    protected List<Capteur> capteur;
    @XmlAttribute(name = "idStation")
    protected Integer idStation;
    @XmlAttribute(name = "nomStation")
    protected String nomStation;

    /**
     * Gets the value of the capteur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capteur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapteur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Capteur }
     * 
     * 
     */
    public List<Capteur> getCapteur() {
        if (capteur == null) {
            capteur = new ArrayList<Capteur>();
        }
        return this.capteur;
    }

    /**
     * Gets the value of the idStation property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdStation() {
        return idStation;
    }

    /**
     * Sets the value of the idStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdStation(Integer value) {
        this.idStation = value;
    }

    /**
     * Gets the value of the nomStation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomStation() {
        return nomStation;
    }

    /**
     * Sets the value of the nomStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomStation(String value) {
        this.nomStation = value;
    }

}
