//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.24 at 02:13:20 AM CET 
//


package modeleMessages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Train complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Train">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capteur" type="{http://www.example.org/MockTrain}Capteur" maxOccurs="unbounded"/>
 *         &lt;element name="position" type="{http://www.example.org/MockTrain}Canton"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idTrain" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="nomTrain" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Train", propOrder = {
    "capteur",
    "position"
})
public class Train {

    @XmlElement(required = true)
    protected List<Capteur> capteur;
    @XmlElement(required = true)
    protected Canton position;
    @XmlAttribute(name = "idTrain")
    protected Integer idTrain;
    @XmlAttribute(name = "nomTrain")
    protected String nomTrain;

    /**
     * Gets the value of the capteur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capteur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapteur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Capteur }
     * 
     * 
     */
    public List<Capteur> getCapteur() {
        if (capteur == null) {
            capteur = new ArrayList<Capteur>();
        }
        return this.capteur;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Canton }
     *     
     */
    public Canton getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Canton }
     *     
     */
    public void setPosition(Canton value) {
        this.position = value;
    }

    /**
     * Gets the value of the idTrain property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdTrain() {
        return idTrain;
    }

    /**
     * Sets the value of the idTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdTrain(Integer value) {
        this.idTrain = value;
    }

    /**
     * Gets the value of the nomTrain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomTrain() {
        return nomTrain;
    }

    /**
     * Sets the value of the nomTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomTrain(String value) {
        this.nomTrain = value;
    }

}
